image: node:14

# Build process
snapcraft:amd64:
  before_script:
    - pwd
  script:
    - npm run src:clone && npm run build
  artifacts:
     paths:
      - snap/dogehouse-src/baklava/builds

# Publish to Snap Store
# ref: https://circleci.com/docs/2.0/build-publish-snap-packages/
.snapcraft:publish:
  image: cibuilds/snapcraft
  dependencies:
    # - snapcraft:arm64
    - snapcraft:amd64
  script:
    # see https://circleci.com/docs/2.0/build-publish-snap-packages/?section=deployment#publishing
    # in case of GitLab CI, add your $SNAPCRAFT_LOGIN_FILE into your project's Variables in CI settings.
    - echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage > snapcraft-login.txt && snapcraft login --with snapcraft-login.txt
    - cp -rv snap/dogehouse-src/baklava/builds/*.snap .
    - |
      for i in *.snap
      do
        # available options for release: edge, beta, candidate, stable
        echo "Publishing $i into Snap Store..."
        sleep 5
        snapcraft push $i --release edge || echo "Push failed! Aborting..." && exit 1
      done
  only:
    branches:
      # edit this if your main branch name is different
      - master
