name: dogehouse # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Taking conversations into the moon # 79 char long summary
description: |
  DoegHouse is an Discord-like voice chats service, powered by
  DogeCoins.

confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
