name: dogehouse
version: '0.1'
summary: Taking conversations into the moon
description: |
  DoegHouse is an Discord-like voice chats service, powered by
  DogeCoin, to take voice-based conversations into the moon.

compression: lzo

# Chnage this into strict once the essentials are added
confinement: devmode

# Ensure that keep things up-to-date with the latest LTS as possible
# but since Gnome 3.x wants Ububtu Core 18, we need to change that
# ibto core18 until they support Core 20 finally.
base: core18

# WORK IN PROGRESS / PLEASE PROCEED AT YOUR OWN RISK
# Sidenote: This was copied from https://www.electronjs.org/docs/tutorial/snapcraft#step-1-create-sample-snapcraft-project
# and requires additional work and testing.
apps:
  dogehouse:
    command: dogehouse/dogehouse --no-sandbox
    extensions: [gnome-3-28]
    plugs:
    - network
    - network-bind
    - audio-playback
    - network-status
    - microphone
    - x11
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to ensure
      # libappindicator has readable resources.
      TMPDIR: $XDG_RUNTIME_DIR
parts:
  dogehouse:
    plugin: nil
    source: https://github.com/benawad/dogehouse.git
    override-build: |
        cd baklava
        npm install electron electron-packager
        npx electron-packager . DogeHouse --icon=./icons/icon.png --overwrite --platform=linux --output=release-build --prune=true
        cp -rv ./DogeHouse-* $SNAPCRAFT_PART_INSTALL/dogehouse
    build-snaps:
    - node/14/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4
