name: dogehouse
version: '0.1'
summary: Taking voice conversations to the moon 🚀
description: |
  Livestream Discord-like voice rooms

  To open the app, just type 'dogehouse' on your terminal. Desktop icon soon.

# Since we're still testing the Electron app, we'll go into
# the edge/devel channel.
grade: devel

# Chnage this into strict once the essentials are added
confinement: devmode

# Ensure that keep things up-to-date with the latest LTS as possible
# but since Gnome 3.x wants Ububtu Core 18, we need to change that
# into core18 until they support Core 20 finally.
base: core18

# No 32-bit (i386) support as per git-branch:staging:
# baklava/package.json scripts. And also I don't like to
# mess up with arm64 again.
architectures:
  - build-on: amd64
    run-on: amd64
  #- build-on: arm64
  #  run-on: arm64

# WORK IN PROGRESS / PLEASE PROCEED AT YOUR OWN RISK
# Sidenote: This was copied from https://www.electronjs.org/docs/tutorial/snapcraft#step-1-create-sample-snapcraft-project
# and requires additional work and testing.
apps:
  dogehouse:
    command: DogeHouse/DogeHouse --no-sandbox
    # TODO: Migrate to latest LTS, the docs for migration is still WIP.
    extensions: [gnome-3-28]
    plugs:
      - network
      - network-observe
      - pluseaudio
      - system-observe
      - x11
      - desktop
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to ensure
      # libappindicator has readable resources.
      TMPDIR: $XDG_RUNTIME_DIR
parts:
  dogehouse:
    plugin: nil
    source: https://github.com/benawad/dogehouse.git
    source-branch: staging
    build-environment:
      - PATH: "$PATH:$SNAPCRAFT_PART_BUILD/node_modules/.bin"
    override-build: |
        PATH=$PATH:$SNAPCRAFT_PART_SRC/../npm/bin
        export NPM_PATH=$(command -v npm)
        export NODEJS_PATH=$(command -v node)
        $NPM_PATH config set unsafe-perm True

        # workaround for build.snapcraft.io builds
        # https://bugs.launchpad.net/bugs/1886861
        if [ -n "$http_proxy" ]; then
           echo "Proxy detected! It's at ${http_proxy}"
           export ELECTRON_GET_USE_PROXY=1
           export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
           export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
           npm config set proxy ${http_proxy}
           npm config set https-proxy ${http_proxy}
           npm config set strict-ssl false
        else
           echo "No proxy detected, skipping configuring proxy stuff..."
        fi

        # install Yarn first
        cd baklava
        echo "==> Installing Yarn..."
        DEBUG=* sudo $NPM_PATH --unsafe --without-ssl install yarn -g
        export YARN_PATH=$(command -v yarn)
        if [ -n "${http_proxy}" ]; then
          yarn config set strict-ssl false
        fi

        # finally, install build deps
        echo "==> Installing and building overlay deps..."
        cd resources/overlay
        DEBUG=* $YARN_PATH
        DEBUG=* $YARN_PATH build
        cd ../..

        echo "==> Installing build deps..."
        DEBUG=* $YARN_PATH install
        cargo install nj-cli

        echo "==> Building Electron app..."
        DEBUG=* $YARN_PATH build:globkey
        DEBUG=* $YARN_PATH build:linux

        echo "==> CopyIng build files into ${SNAPCRAFT_PART_INSTALL}..."
        cp -rv ./builds/DogeHouse-* $SNAPCRAFT_PART_INSTALL/DogeHouse

        # for validation purposes only
        echo "==> Validating if copied successfully..."
        ls $SNAPCRAFT_PART_INSTALL -al
        ls $SNAPCRAFT_PART_INSTALL/DogeHouse -al || echo "You didn't copied built fipes into the SNAPCRAFT_PART_INSTALL, aborting..." && exit 1

        # Desktop Icons stuff
        #sed -i 's|Icon=DogeHouse|Icon=${SNAP}/meta/gui/dogehouse\.png|g' ${SNAP}/meta/gui/dogehouse.desktop
    build-snaps:
    - node/14/stable
    build-packages:
    - unzip
    - libcurl4
    - wget
    - libxkbcommon-x11-0
    - cargo
    - rustc
    stage-packages:
    - libnss3
    - libnspr4
