name: Build and Release Snap
 
on:
  push:
    branches:
    - master
 
jobs:
  build-stable:
    runs-on: ubuntu-latest
    
    # Let's build for many architectures..
    strategy:
      matrix:
        architecture:
        - linux/amd64
        - linux/386
        - linux/arm64
        - linux/arm/v7
    steps:
    # Checkout the code of our Repository
    - uses: actions/checkout@v2

    - name: Snap DogeHouse Electrob app
      uses: diddlesnaps/snapcraft-multiarch-action@v1
      id: snapcraft

    - name: Archive as Action Artifact on Snapcrafters Archive soon
      uses: actions/upload-artifact@v2
      with:
        name: 'snapcrafters-archive.thepinsteam.dev/@snapcrafters-bot/dogehouse-app-artifacts'
        path: ${{ steps.snapcraft.outputs.snap }}

    # Release this Snap to the channel we choose.
    #- uses: snapcore/action-publish@v1
    #  with:
    #    store_login: ${{ secrets.STORE_LOGIN }}
    #    snap: ${{ steps.build.outputs.snap }}
    #    release: beta
